### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by schwal10** [schwal10/lunatic-fringe#18]
Clean up the code. There are a lot of places where the coding could be better and simpler.
Example: handling collisions/collision sounds

**Comment by schwal10** [comment]
- [x] Clean up handling collisions/collision sounds
- [x] Handling of player powerups
- [x] Move each object into its own file

**Comment by jackinloadup** [comment]
Just saw your fork here. Amazing work! :+1:

**Comment by schwal10** [comment]
@jackinloadup Thanks! I plan on creating a pull request into your repository with what I have so far once I clean up the code a bit more.

**Comment by schwal10** [comment]
Code has been refactored so that objects have their own files, making the code easier to maintain.
